language: go
go_import_path: github.com/gcash/bchd
go:
  - "1.12.17"
  - "1.13.10"
  - "1.14.2"

sudo: false

cache:
  directories:
    - $GOPATH/pkg/mod
    - /home/travis/.cache/go-build

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1

install:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go install . ./cmd/...

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh

after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.14.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/inconshreveable/mousetrap; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.14.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/mitchellh/gox; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.14.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/tcnksm/ghr; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.14.2" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then make compile; ghr --username gcash --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi
