language: go
go:
  - "1.9.5"
  - "1.10.1"
sudo: false

before_install:
  - >-
    curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
    -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install

install:
  - dep ensure
  - go install . ./cmd/...

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - ./goclean.sh

